### ISSUE TITLE
Request Blog

### ISSUE THREAD

**Issue by wesleyel** [dragonxtek/iperf_dissector#2]
Nice job! 

Your blog(https://installfights.blogspot.cl/2016/10/install-wireshark-23-on-ubuntu-1604.html) seems to be unavailable. 
Is there a backup?

Regards

**Comment by dragonxtek** [comment]
I don't have issues to load the page. Maybe you have some restrictions. Try with an online web proxy like [this](https://us20.proxysite.com/process.php?d=d0qhHruMmJBYTEq0FfIi4wkiVhk19l0VJ01cLPQAdczQENXQUnDTuxGo6Ff0AWtEUNWJm5bFiL3heFInFQU2P0MCrZLMoTMl661n4KzBYg%3D%3D&b=1&f=norefer)
